-- 1. 카테고리 테이블 (CATEGORIES)
-- 카테고리 ID (CATEGORY_ID) - NUMBER [PK]
-- 카테고리 이름 (CATEGORY_NAME) - VARCHAR2(100) [UNIQUE]

CREATE TABLE CATEGORIES(
	CATEGORY_ID NUMBER PRIMARY KEY, 
	CATEGORY_NAME VARCHAR2(100) UNIQUE
);

COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS '카테고리 ID';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS '카테고리 이름';

INSERT INTO CATEGORIES VALUES(1, '스마트폰');
INSERT INTO CATEGORIES VALUES(2, 'TV');
INSERT INTO CATEGORIES VALUES(3, 'Gaming');

SELECT * FROM CATEGORIES;

/*2. 상품 정보 테이블 (PRODUCTS)
상품 코드 (PRODUCT_ID) - NUMBER [PK]
상품 이름 (PRODUCT_NAME) - VARCHAR2(100) [NOT NULL]
카테고리 (CATEGORY) - NUMBER [FK - CATEGORIES(CATEGORY_ID)]
가격 (PRICE) - NUMBER [DEFAULT 0]
재고량 (STOCK_QUANTITY) NUMBER [DEFAULT 0]
 * */
CREATE TABLE PRODUCTS(
	PRODUCT_ID NUMBER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(100) NOT NULL,
	CATEGORY NUMBER CONSTRAINT CATEGORIES_FK REFERENCES CATEGORIES,
	PRICE NUMBER DEFAULT 0,
	STOCK_QUANTITY NUMBER DEFAULT 0
);

COMMENT ON COLUMN PRODUCTS.PRODUCTS IS '상품 코드';
COMMENT ON COLUMN PRODUCTS.PRODUCT_NAME IS '상품 이름';
COMMENT ON COLUMN PRODUCTS.CATEGORY IS '카테고리';
COMMENT ON COLUMN PRODUCTS.PRICE IS '가격';
COMMENT ON COLUMN PRODUCTS.STOCK_QUANTITY IS '재고량';

INSERT INTO PRODUCTS VALUES(101, 'Apple iPhone12', 1, 1500000, 30);
INSERT INTO PRODUCTS VALUES(102, 'Samsung Galaxy S24', 1, 1800000, 50);
INSERT INTO PRODUCTS VALUES(201, 'LG OLED TV', 2, 3600000, 10);
INSERT INTO PRODUCTS VALUES(301, 'Sony PlayStation 5', 3, 700000, 15);

SELECT * FROM PRODUCTS;

/*3. 고객 정보 테이블 (CUSTOMERS)
고객 ID (CUSTOMER_ID) - NUMBER [PK]
이름 (NAME) - VARCHAR2(20) [NOT NULL]
성별 (GENDER) - CHAR(3) [CHECK 남, 여]
주소 (ADDRESS) - VARCHAR2(100)
전화번호 (PHONE) - VARCHAR2(30)
 * */
CREATE TABLE CUSTOMERS(
	CUSTOMER_ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	GENDER CHAR(3) CONSTRAINT GENDER_CHECK CHECK(GENDER IN ('남', '여')),
	ADDRESS VARCHAR2(100),
	PHONE VARCHAR2(30)
);

COMMENT ON COLUMN CUSTOMERS.CUSTOMERS IS '고객 ID';
COMMENT ON COLUMN CUSTOMERS.NAME IS '이름';
COMMENT ON COLUMN CUSTOMERS.GENDER IS '성별';
COMMENT ON COLUMN CUSTOMERS.ADDRESS IS '주소';
COMMENT ON COLUMN CUSTOMERS.PHONE IS '전화번호';

INSERT INTO CUSTOMERS VALUES(1, '홍길동', '남', '서울시 성동구 왕십리', '010-1111-2222');
INSERT INTO CUSTOMERS VALUES(2, '유관순', '여', '서울시 종로구 안국동', '010-3333-1111');

SELECT * FROM CUSTOMERS;

/*4. 주문 정보 테이블 (ORDERS)
주문 번호 (ORDER_ID) - NUMBER [PK]
주문일 (ORDER_DATE) - DATE [DEFAULT SYSDATE]
처리상태 (STATUS) - CHAR(1) DEFAULT 'N' [CHECK ('Y', 'N') ]
고객 ID (CUSTOMER_ID) - NUMBER [FK - CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE]
 * */

CREATE TABLE ORDERS(
	ORDER_ID NUMBER PRIMARY KEY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CONSTRAINT STATUS_CHECK CHECK(STATUS IN ('Y', 'N')),
	CUSTOMER_ID NUMBER CONSTRAINT CUSTOMER_ID_FK REFERENCES CUSTOMERS ON DELETE CASCADE
);

COMMENT ON COLUMN ORDERS.ORDER_ID IS '주문 번호';
COMMENT ON COLUMN ORDERS.ORDER_DATE IS '주문일';
COMMENT ON COLUMN ORDERS.STATUS IS '처리상태';
COMMENT ON COLUMN ORDERS.CUSTOMER_ID IS '고객 ID';

INSERT INTO ORDERS VALUES(576, '2024-02-29', 'N', 1);
INSERT INTO ORDERS VALUES(978, '2024-03-11', 'Y', 2);
INSERT INTO ORDERS VALUES(777, '2024-03-11', 'N', 2);
INSERT INTO ORDERS VALUES(134, '2022-12-25', 'Y', 1);
INSERT INTO ORDERS VALUES(499, '2020-01-03', 'Y', 1);

SELECT * FROM ORDERS;

/*5. 주문 상세 정보 테이블 (ORDER_DETAILS)
주문 상세 ID (ORDER_DETAIL_ID) - NUMBER [PK]
주문 번호 (ORDER_ID) NUMBER - [FK - ORDERS(ORDER_ID) ON DELETE CASCADE]
상품 코드 (PRODUCT_ID) NUMBER - [FK - PRODUCTS(PRODUCT_ID) ON DELETE SET NULL]
수량 (QUANTITY) NUMBER
가격 (PRICE_PER_UNIT) NUMBER
 * */
CREATE TABLE ORDER_DETAILS(
	ORDER_DETAIL_ID NUMBER PRIMARY KEY,
	ORDER_ID NUMBER CONSTRAINT ORDER_ID_FK REFERENCES ORDERS ON DELETE CASCADE,
	PRODUCT_ID NUMBER CONSTRAINT PRODUCT_ID_FK REFERENCES PRODUCTS ON DELETE SET NULL,
	QUANTITY NUMBER,
	PRICE_PER_UNIT NUMBER
);

COMMENT ON COLUMN ORDER_DETAILS.ORDER_DETAIL_ID IS '주문 상세 ID';
COMMENT ON COLUMN ORDER_DETAILS.ORDER_ID IS '주문 번호';
COMMENT ON COLUMN ORDER_DETAILS.PRODUCT_ID IS '상품 코드';
COMMENT ON COLUMN ORDER_DETAILS.QUANTITY IS '수량';
COMMENT ON COLUMN ORDER_DETAILS.PRICE_PER_UNIT IS '가격';

INSERT INTO ORDER_DETAILS VALUES(111, 576, 101, 1, 1500000);
INSERT INTO ORDER_DETAILS VALUES(222, 978, 201, 2, 3600000);
INSERT INTO ORDER_DETAILS VALUES(333, 978, 102, 1, 1800000);
INSERT INTO ORDER_DETAILS VALUES(444, 777, 301, 5, 700000);
INSERT INTO ORDER_DETAILS VALUES(555, 134, 102, 1, 1800000);
INSERT INTO ORDER_DETAILS VALUES(666, 499, 201, 3, 3600000);

SELECT * FROM ORDER_DETAILS;

COMMIT;

/*1. 쇼핑몰 관리자가 주문은 받았으나, 아직 처리가 안된 주문을 처리하려고
한다. 현재 주문 내역 중 아직 처리되지 않은 주문을 조회하시오. 😀
(고객명, 주문일, 처리상태)
 * */
SELECT NAME "고객명", ORDER_DATE "주문일", STATUS "처리상태"
FROM CUSTOMERS
JOIN ORDERS USING(CUSTOMER_ID)
WHERE STATUS = 'N';

/*2. 홍길동 고객이 2024년도에 본인이 주문한 전체 내역을 조회하고자 한다.
주문번호, 주문날짜, 처리상태 조회하시오 😀
 * */
SELECT ORDER_ID 주문번호, ORDER_DATE 주문날짜, STATUS 처리상태
FROM ORDERS
JOIN CUSTOMERS USING(CUSTOMER_ID)
WHERE NAME = '홍길동'
AND EXTRACT(YEAR FROM ORDER_DATE) = 2024;

/*3. 유관순 고객이 지금껏 주문한 상품의 수량 별 금액을 조회하려고 한다.
주문번호, 상품명, 수량, 개별금액, 주문별금액을 조회하시오 😀
 * */
SELECT ORDER_ID "주문번호", PRODUCT_NAME "상품명", QUANTITY "수량", 
PRICE_PER_UNIT "개별금액", (QUANTITY*PRICE_PER_UNIT) "주문별금액합계"
FROM ORDERS -- 주문번호
JOIN ORDER_DETAILS USING(ORDER_ID) -- 수량, 개별금액
JOIN PRODUCTS USING(PRODUCT_ID) -- 상품명
JOIN CUSTOMERS USING(CUSTOMER_ID)
WHERE NAME = '유관순'
ORDER BY 수량 DESC;








